version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'springbootdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Cvjkdbkm246'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        retries: 10
        interval: 3s
        timeout: 30s
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
          - docker-mysql


  javaservice:
    build:
      context: .
    container_name: javaservice
    depends_on:
      db:
           condition:
                    service_healthy
    ports:
      - "8080:8080"
    networks:
        - docker-mysql
networks:
  docker-mysql:
      driver: bridge

